# settings.yaml

project:
  project_name: "cli_test"     # WandB Project Name / Output Folder Name
  run_name: "roboflow_train"   # Specific Run Name
  output_dir: "./runs"

# data:
#   # Source Selection
#   source: "roboflow"
  
#   # Directory name where data will be extracted inside ./datasets/
#   dataset_name: "bottle_cap_public"
  
#   # Name of the config file inside the downloaded folder
#   yaml_path: "data.yaml"

#   # Roboflow Config
#   roboflow:
#     workspace: "work3-dqzz5"
#     project: "bottle-cap-y6pzg"
#     version: 1

data:
  source: "url"
  dataset_name: "bottle_cap_public"
  yaml_path: "config.yaml"
  url:
    link: "gcs link here"

model:
  # Architecture definition
  name: "yolo11p.yaml" 
  task: "detect"

wandb:
  enabled: true

# Training Hyperparameters
# These match the 'model_p_pretrain.train()' arguments from your snippet
training:
  epochs: 5
  batch: 16             # Standard default, adjust if GPU runs OOM
  imgsz: 640
  device: 'cpu'             # Use 0 for GPU, 'cpu' for CPU
  verbose: true
  
  # Optimizer Settings
  optimizer: "SGD"
  lr0: 0.02
  weight_decay: 0.01
  
  # Augmentation Overrides (from your snippet)
  hsv_h: 0.0            # Hue augmentation
  hsv_s: 0.25           # Saturation augmentation
  hsv_v: 0.0            # Value (Brightness) augmentation
  mixup: 0.0            # Mixup augmentation
  fliplr: 0.5           # Flip Left-Right probability
  mosaic: 0.0           # Mosaic augmentation (Disabled)