# settings.yaml

project:
  project_name: "cli_test"     # WandB Project Name / Output Folder Name
  run_name: "roboflow_train"   # Specific Run Name
  output_dir: "./runs"

# data:
#   # Source Selection
#   source: "roboflow"
  
#   # Directory name where data will be extracted inside ./datasets/
#   dataset_name: "<dataset folder"
  
#   # Name of the config file inside the downloaded folder
#   yaml_path: "data.yaml"

#   # Roboflow Config
#   roboflow:
#     workspace: "<public roboflow workspace id>"
#     project: "<public roboflow project id>"
#     version: 1

data:
  source: "url"
  dataset_name: "<dataset folder>"  # Folder name inside ./datasets/
  yaml_path: "config.yaml"
  url:
    link: "<dataset download link>"

model:
  # Architecture definition
  name: "yolo11p.yaml" 
  task: "detect"

wandb:
  enabled: true

# Training Hyperparameters
training:
  # Refer to https://docs.ultralytics.com/modes/train/ for details
  epochs: 5
  batch: 16
  imgsz: 640
  device: 'cpu' # Use 0 for GPU, 'cpu' for CPU
  verbose: true
  
  # Optimizer Settings
  optimizer: "SGD"
  lr0: 0.02
  weight_decay: 0.01
  
  hsv_h: 0.0            # Hue augmentation
  hsv_s: 0.25           # Saturation augmentation
  hsv_v: 0.0            # Value (Brightness) augmentation
  mixup: 0.0            # Mixup augmentation
  fliplr: 0.5           # Flip Left-Right probability
  mosaic: 0.0           # Mosaic augmentation (Disabled)